### ISSUE TITLE
Erro ao ler dados na versão 0.7

### ISSUE THREAD

**Issue by rdahis** [Gabriel-Assuncao/PNADcIBGE#1]
Rodando esses comandos na versão 0.7:

``` R
input_path <- pnadc_example(path="input_example.txt")
data_path <- pnadc_example(path="exampledata.txt")
pnadc.df <- read_pnadc(microdata=data_path, input_txt=input_path, vars=c("VD4001","VD4002"))
```

eu recebo esse erro:

``` R
Error in substr(X1, 1, 1) : invalid multibyte string, element 1
```

Pode ter a ver com a atualização dos microdados feita pelo IBGE?

**Comment by LeticiaMagalar** [comment]
Oi Gabriel, tudo bem? Eu já atualizei o pacote readr, mas continuo com esse mesmo erro apresentado pelo rdahis.

"Error in substr(X1, 1, 1) : invalid multibyte string, element 1"

Você sabe o que mais pode ser?

**Comment by Gabriel-Assuncao** [comment]
Olá Leticia. Tudo bem sim e contigo?

Irei precisar de algumas informações sobre as versões dos pacotes que estão sendo utilizadas, para isto basta executar os comandos abaixo no software R:

paste0(R.version$major,".",R.version$minor)
packageDescription("PNADcIBGE")$Version
packageDescription("readr")$Version

Assim que executar tais comandos, colete os resultados e me envie aqui por gentileza.

**Comment by jrrmorais** [comment]
Oi Gabriel, estou com o mesmo problema. Rodei o código acima, segue:

> paste0(R.version$major,".",R.version$minor)
[1] "3.6.2"
> packageDescription("PNADcIBGE")$Version
[1] "0.7.0"
> packageDescription("readr")$Version
[1] "1.3.1"

Abs.

**Comment by jrrmorais** [comment]
Havia feito a atualização do readr na versão 3.6 do R, aí não tinha dado certo. Na versão 4.0 do R funcionou, obrigado!
> paste0(R.version$major,".",R.version$minor)
[1] "4.0.2"
> packageDescription("PNADcIBGE")$Version
[1] "0.7.0"
> packageDescription("readr")$Version
[1] "2.1.2"

**Comment by Gabriel-Assuncao** [comment]
Ótimo, é sempre importante realizar a verificação das versões dos pacotes, justamente por conta de mudanças nas estruturas das funções utilizadas.

Sendo assim, irei fechar esta 'issue', qualquer dúvida ou informação que surja, solicito que entre em contato através do canal de atendimento pacotesipd@ibge.gov.br.

**Comment by lhayana** [comment]
Estou tendo o mesmo erro, mesmo com o pacote atualizado.
Pior que funciona com os microdados normais, mas esses de suplemento não.

![image](https://github.com/Gabriel-Assuncao/PNADcIBGE/assets/34015939/7d3c7901-f9f8-4324-a450-86b3c9223b44)

**Comment by Gabriel-Assuncao** [comment]
@lhayana, boa noite.
O pacote _PNADcIBGE_ foi desenvolvido para leitura dos microdados da **PNAD Contínua** e pelo que observei do seu código, as funções do pacote estão sendo utilizadas para leitura dos microdados da **PNAD**, no entanto o pacote não é adequado para leitura da **PNAD** e infelizmente não existe um pacote dedicado para tal pesquisa disponibilizado pelo IBGE.

**Comment by lhayana** [comment]
entendi, muito obrigada!

**Comment by Gabriel-Assuncao** [comment]
Por nada!
Permaneço à disposição através dessa plataforma e também do canal de atendimento pacotesipd@ibge.gov.br.
