### ISSUE TITLE
Não consigo fazer download pelo get_pnadc

### ISSUE THREAD

**Issue by gdcbserafim** [Gabriel-Assuncao/PNADcIBGE#10]
Olá, Gabriel! Não estou conseguindo obter os dados pelo get_pnadc. Aparece esse erro: 

> get_pnadc(2022,1)
Testing for internet connectivity via https_proxy... success!
Error in function (type, msg, asError = TRUE)  : 
  schannel: CertGetCertificateChain trust error CERT_TRUST_IS_UNTRUSTED_ROOT
  
  Poderia me ajudar?

**Comment by Gabriel-Assuncao** [comment]
Prezado @gdcbserafim, bom dia.

Aparentemente o erro encontrado está relacionado às permissões de certificado configurados em seu computador ou no seu software R, pois realizamos o mesmo teste para obtenção dos microdados do 1º trimestre de 2022 em diferentes computadores e conseguimos obter sem presenciar o mesmo problema.

Vasculhamos um pouco pela internet sobre tal problema e encontramos uma possível solução que está apresentada em uma das respostas no link a seguir: https://stackoverflow.com/questions/57198836/how-to-fix-certgetcertificatechain-trust-error-cert-trust-is-untrusted-root-in-r, onde é feita a alteração da configuração de uma opção do pacote httr através do comando httr::set_config(httr::config(ssl_verifypeer=0L)), verifique por gentileza se tal solução se aplica a seu caso também.

Se por ventura o problema for corrigido, pedimos por gentileza que feche esta issue, caso contrário nos escreva novamente por aqui ou através do e-mail pacotesipd@ibge.gov.br para que possamos tentar lhe auxiliar novamente.

Esperamos que as informações acima possam ser suficientes para sanar as dúvidas apresentadas, no entanto caso ainda haja alguma pendência, pedimos por gentileza que entre em contato novamente.

Sendo assim, agradecemos imensamente pela atenção e estamos à disposição para qualquer eventualidade.

Regards,
SIPDIBGE, PNADcIBGE, POFIBGE [Archived], PNSIBGE and COVIDIBGE Packages Support

**Comment by Gabriel-Assuncao** [comment]
Outro problema poderia ser por estar utilizando uma rede corporativa ou pública, como de uma empresa ou universidade, e esta rede não permitir o acesso ao servidor do IBGE através do software R impossibilitando de realizar o download e obtenção dos microdados através da função get_pnadc.

É possível sim realizar o subset mantendo somente as variáveis de interesse nos microdados a partir da função read_pnadc, para isso basta utilizar o argumento vars, da mesma forma como é feito na função get_pnadc. Sendo importante mencionar, que mesmo que o usuário selecione algumas variáveis específicas dos microdados, durante a rotina são mantidas as variáveis essenciais para as demais etapas de compilação dos microdados com o intuito de incorporar o desenho amostral para obter os resultados em nível populacional corretamente, então ao realizar este procedimento serão mantidas nos microdados 215 variáveis essenciais (incluindo as replicações dos pesos de bootstrap que fazem parte da nova metodologia de ponderação da PNAD Contínua) mais as variáveis que foram inseridas no argumento vars pelo usuário, e subtrai-se desta conta interseções entre variáveis essenciais que eventualmente também possam ter sido indicadas no argumento vars pelo usuário.

Ficamos no aguardo do retorno para saber se de fato conseguimos realizar o atendimento solicitado, para que então possamos prosseguir com o fechamento desta issue.
