### ISSUE TITLE
get_pnadc retornando erro ao tentar baixar pnadc 2022 visita 1

### ISSUE THREAD

**Issue by pgesteirads** [Gabriel-Assuncao/PNADcIBGE#13]
Olá Gabriel, parabéns pelo pacote!

Estou tendo problemas em executar a função get_pnadc com os seguintes parâmetros:

`PNADcIBGE::get_pnadc(2022, interview = 1, design = FALSE)
`

Ele me retorna o seguinte erro:

`Error in as.environment(where) : 
  no item called "package:PNADcIBGE" on the search list`

**Comment by Gabriel-Assuncao** [comment]
Prezado Pedro Gesteira, boa tarde.

Ficamos gratos em saber que o pacote fornecido tem sido útil em seus trabalhos.

Sobre o erro indicado, tal erro ocorre geralmente quando o pacote ainda não foi instalado, ou quando o pacote foi instalado e ainda não foi carregado.

Para instalar o pacote PNADcIBGE basta utilizar o comando abaixo:
install.packages(pkgs="PNADcIBGE")

Já para carregar o pacote PNADcIBGE após tê-lo instalado, basta utilizar o comando abaixo:
library(package="PNADcIBGE")
Lembrando que toda vez que for aberta uma nova sessão do R ou RStudio é necessário fazer esse procedimento de carregamento novamente, antes da utilização efetiva das funções do pacote.

Após a realização dos procedimentos acima citados, acreditamos que o erro será solucionado e os microdados serão obtidos corretamente.

Irei fechar esse _issue_, mas qualquer dúvida ou dificuldade que surgir, fique a vontade para abrir novamente ou entre em contato diretamente através do canal de atendimento pacotesipd@ibge.gov.br.
