### ISSUE TITLE
Criação de variável 

### ISSUE THREAD

**Issue by Demografia-UFS** [Gabriel-Assuncao/PNADcIBGE#14]
Gabriel, 
Estou tentando recriar a renda domiciliar originada do trabalho com a PnadC 2016 5ª visita. O objetivo é somar as rendas de todos os componentes do domicílio. Para isso, penso que a forma de agregação é UPA - Estrato - V1002.  
O script abaixo soma todas as rendas (sem agrupar):
pnadc_2016_calib_se <- update(pnadc_2016_calib_se,
                              y_hab_trab = mean(VD4019, na.rm = T),
                              y_efet_trab = mean(VD4020, na.rm = T),
                              bpc = mean(V5001A2, na.rm = T),
                              pbf = mean(V5002A2, na.rm = T),
                              out_psoc = mean(V5003A2, na.rm = T),
                              aposent = mean(V5004A2, na.rm = T),
                              seg_desemp = mean(V5005A2, na.rm = T),
                              pens_alim = mean(V5006A2, na.rm = T),
                              aluguel = mean(V5007A2, na.rm = T),
                              ativos = mean(V5008A2, na.rm = T),
                              y_dom = y_hab_trab + bpc + pbf + out_psoc + aposent + seg_desemp + pens_alim + aluguel + ativos
)

Minha pergunta é: como fazer isso utilizando o "update", uma vez que já incorporei o plano amostral?

Obrigado e parabéns pelo belíssimo pacote.
Kleber Oliveira - Universidade Federal de Sergipe

P.S
Eu consegui fazer isto antes de incorporar o desenho amostral, conforme segue:
pnadc_2016 <- pnadc_2016 %>% 
  group_by(UPA, Estrato, V1008) %>% 
  mutate(y_hab_trab = sum(VD4019, na.rm = T),
         y_efet_trab = sum(VD4020, na.rm = T),
         bpc = sum(V5001A2, na.rm = T),
         pbf = sum(V5002A2, na.rm = T),
         out_psoc = sum(V5003A2, na.rm = T),
         aposent = sum(V5004A2, na.rm = T),
         seg_desemp = sum(V5005A2, na.rm = T),
         pens_alim = sum(V5006A2, na.rm = T),
         aluguel = sum(V5007A2, na.rm = T),
         ativos = sum(V5008A2, na.rm = T),
         y_dom = y_hab_trab + bpc + pbf + out_psoc + aposent + seg_desemp + pens_alim + aluguel + ativos
         )

**Comment by Gabriel-Assuncao** [comment]
Prezado Kleber Oliveira, boa noite.

Disponibilizamos através do GitHub uma rotina justamente para obtenção do rendimento domiciliar e do rendimento domiciliar per capita em valores reais, ou seja, com o deflacionamento das variáveis de rendimento que compõem o rendimento domiciliar. Esta rotina pode ser acessada através do endereço [https://github.com/Gabriel-Assuncao/PNADcIBGE-RDPC/blob/main/PNADcIBGE-RDPC.R](https://github.com/Gabriel-Assuncao/PNADcIBGE-RDPC/blob/main/PNADcIBGE-RDPC.R).

Sendo importante indicar que tal rotina é implementada justamente antes da incorporação do desenho amostral, para que possamos fazer os agrupamentos e cálculos em nível de domicílio e então juntar com a base de origem, para só depois disso realizar a incorporação do desenho amostral para obtenção das estimativas em valores populacionais.

Assim, indicamos que verifique a rotina disponibilizada, indicada anteriormente, pois creio que tal rotina lhe auxiliará na obtenção dos resultados desejados. No entanto, caso surja alguma dúvida ou dificuldade, pedimos por gentileza que entre em contato através do canal de atendimento [pacotesipd@ibge.gov.br](pacotesipd@ibge.gov.br).

Diante disso, estaremos fechando esta issue e ficamos à disposição através do canal mencionado anteriormente.

**Comment by Demografia-UFS** [comment]
Obrigado, Gabriel. Excelente dica.
Um abraço
