### ISSUE TITLE
Scritp para estimar o nem-nem

### ISSUE THREAD

**Issue by Demografia-UFS** [Gabriel-Assuncao/PNADcIBGE#15]
Prezado Gabriel, 
     Seria possível disponibilizar o script que estima o nem-nem?

**Comment by Gabriel-Assuncao** [comment]
Prezado Kleber Oliveira, boa noite.

Conforme solicitado, segue abaixo o código para obtenção da proporção de nem-nem entre jovens de 15 a 29 anos, relacionada à tabela 7205 do SIDRA, que pode ser acessada pelo endereço [https://sidra.ibge.gov.br/Tabela/7205](https://sidra.ibge.gov.br/Tabela/7205):

library("PNADcIBGE")
library("survey")
pnadc_anual_trimestre <- get_pnadc(year=2022, topic=2)
pnadc_anual_trimestre$variables <- transform(pnadc_anual_trimestre$variables, MV3002=as.factor(ifelse(is.na(V3002),"Não aplicável",as.character(V3002))))
pnadc_anual_trimestre$variables <- transform(pnadc_anual_trimestre$variables, MV3019A=as.factor(ifelse(is.na(V3019A),"Não aplicável",as.character(V3019A))))
pnadc_anual_trimestre$variables <- transform(pnadc_anual_trimestre$variables, MV3024=as.factor(ifelse(is.na(V3024),"Não aplicável",as.character(V3024))))
pnadc_anual_trimestre$variables <- transform(pnadc_anual_trimestre$variables, MV3025=as.factor(ifelse(is.na(V3025),"Não aplicável",as.character(V3025))))
pnadc_anual_trimestre$variables <- transform(pnadc_anual_trimestre$variables, MV3026=as.factor(ifelse(is.na(V3026),"Não aplicável",as.character(V3026))))
svytotal(x=~as.integer(V2009>=15 & V2009<=29), design=pnadc_anual_trimestre, na.rm=TRUE)
print(x=proporcao_nemnem <- svymean(x=~as.integer(((VD4001=="Pessoas na força de trabalho" & VD4002=="Pessoas desocupadas") | VD4001=="Pessoas fora da força de trabalho") & (MV3002!="Sim" & (MV3019A!="Sim, curso técnico de nível médio" & MV3019A!="Sim, curso normal (magistério)") & MV3024!="Sim" & MV3025!="Sim" & MV3026!="Sim")), design=subset(pnadc_anual_trimestre, V2009>=15 & V2009<=29), na.rm=TRUE))
cv(object=proporcao_nemnem)

É importante destacar que para obtenção de tal estimativa é estritamente necessária a utilização dos microdados anuais concentrados no 2º trimestre de cada ano. Além disso, para os anos anteriores a 2019 é preciso adaptar o código acima trocando as utilizações da variável V3019A pela variável V3019.

Então, caso surja alguma dúvida ou dificuldade na utilização do código fornecido, pedimos por gentileza que entre em contato através do canal de atendimento [pacotesipd@ibge.gov.br](pacotesipd@ibge.gov.br).

Diante disso, estaremos fechando esta _issue_ e ficamos à disposição através do canal mencionado anteriormente.
