### ISSUE TITLE
any guess why these have changed to character types?  they were previously numeric..  thanks!!

### ISSUE THREAD

**Issue by ajdamico** [Gabriel-Assuncao/PNADcIBGE#16]
library(PNADcIBGE)

	pnadc_df <-
	  get_pnadc(2022 ,
				interview = 5 ,
				design = FALSE ,
				labels = FALSE)

	sapply( pnadc_df[ c( 'VD4019' , 'VD4048' ) ] , class )

	# > sapply( pnadc_df[ c( 'VD4019' , 'VD4048' ) ] , class )
		 # VD4019      VD4048 
	# "character" "character" 
	# > sessionInfo()
	# R version 4.3.2 (2023-10-31 ucrt)
	# Platform: x86_64-w64-mingw32/x64 (64-bit)
	# Running under: Windows 10 x64 (build 19045)

	# Matrix products: default

	# locale:
	# [1] LC_COLLATE=English_United States.utf8  LC_CTYPE=English_United States.utf8   
	# [3] LC_MONETARY=English_United States.utf8 LC_NUMERIC=C                          
	# [5] LC_TIME=English_United States.utf8    

	# time zone: America/New_York
	# tzcode source: internal

	# attached base packages:
	# [1] stats     graphics  grDevices utils     datasets  methods   base     

	# other attached packages:
	# [1] PNADcIBGE_0.7.4

	# loaded via a namespace (and not attached):
	 # [1] Matrix_1.6-0      bit_4.0.5         archive_1.1.5     dplyr_1.1.2       compiler_4.3.2   
	 # [6] crayon_1.5.2      tidyselect_1.2.0  bitops_1.0-7      parallel_4.3.2    survey_4.2-1     
	# [11] splines_4.3.2     readxl_1.4.3      lattice_0.21-9    readr_2.1.4       R6_2.5.1         
	# [16] generics_0.1.3    curl_5.0.2        tibble_3.2.1      timeDate_4022.108 DBI_1.1.3        
	# [21] pillar_1.9.0      tzdb_0.4.0        rlang_1.1.1       utf8_1.2.3        bit64_4.0.5      
	# [26] cli_3.6.1         withr_2.5.0       magrittr_2.0.3    grid_4.3.2        vroom_1.6.3      
	# [31] hms_1.1.3         lifecycle_1.0.3   vctrs_0.6.3       glue_1.6.2        cellranger_1.1.0 
	# [36] projmgr_0.1.0     mitools_2.4       survival_3.5-7    RCurl_1.98-1.12   fansi_1.0.4      
	# [41] httr_1.4.7        tools_4.3.2       pkgconfig_2.0.3  
	# >

**Comment by Gabriel-Assuncao** [comment]
Good evening Anthony Damico.
We have already identified the problem and it is related to the input file of such microdata, which was updated along with the disclosure of child labor in the research that took place today.
The responsible team has already been contacted and we hope that the problem will be corrected soon.
Regards,
Gabriel Assuncao.

**Comment by ajdamico** [comment]
thanks!!

**Comment by ajdamico** [comment]
do you have any guess when this might be resolved?  we're unable to build our markdown textbook while this is broken, so it'd be helpful to know if i need to write a patch..  thank you!

**Comment by Gabriel-Assuncao** [comment]
Good afternoon Anthony Damico.
The responsible team provided a forecast for resolving the problem by next Wednesday.
If you prefer, you can provisionally use the input file that I corrected manually and I am providing as an attachment, reading it offline through the package PNADcIBGE using the read_pnadc function.
I'm sorry for what happened and I'm at your disposal for any eventuality.
Regards,
Gabriel Assuncao.
[input_PNADC_2022_visita5_20231220.txt](https://github.com/Gabriel-Assuncao/PNADcIBGE/files/13743798/input_PNADC_2022_visita5_20231220.txt)

**Comment by ajdamico** [comment]
a fix by next wednesday is perfect, thank you!

**Comment by Gabriel-Assuncao** [comment]
Good afternoon Anthony Damico.
I inform you that the input file has already been corrected on the IBGE server, so it is now possible to obtain the microdata from the 5th interview of 2022 without the problem that was occurring previously.
I would like to take this opportunity to thank you for your alert regarding this situation.
With this comment I will close this issue.
Regards,
Gabriel Assuncao.

**Comment by ajdamico** [comment]
thank you!!
