### ISSUE TITLE
Problema com o SSL

### ISSUE THREAD

**Issue by hhmacedo** [Gabriel-Assuncao/PNADcIBGE#17]
Olá, @Gabriel-Assuncao, tudo bom? Eu estou com o mesmo problema reportado em #10 e a solução do  `httr::set_config(httr::config(ssl_verifypeer=0L))` não funciona.

Uma forma de fazer funcionar é passando o parâmetro `.opts = list(ssl.verifypeer = FALSE)` dentro do `RCurl::getURL()`. Se puder, minha sugestão seria que você botasse um parâmetro na função `get_pnadc()` ("rcurl", talvez?) que aceitasse uma lista e, em caso de não nulo, passasse essa lista para dentro do parâmetro `.opts` do `RCurl::getURL()`. Abaixo está uma lista das funções do seu código que imagino que precisariam receber esse parâmetro:

https://github.com/search?q=repo%3AGabriel-Assuncao%2FPNADcIBGE%20RCurl%3A%3AgetURL&type=code

**Comment by Gabriel-Assuncao** [comment]
Prezado Hugo Macedo, boa tarde.
Agradeço imensamente pela sugestão, irei adicionar este argumento na função get_pnadc na próxima atualização do pacote PNADcIBGE que prevejo para ocorrer agora em fevereiro de 2024.
Como irei adotar a abordagem indicada, estarei definindo esta issue como fechada, mais uma vez agradeço pelo feedback.

**Comment by hhmacedo** [comment]
Uma outra solução, que daria um pouquinho mais de trabalho e pode ficar para uma versão mais avançada, é substituir o uso do RCurl pelo httr2. Segundo o @jjesusfilho me informou, esse seria uma migração que vem acontecendo recentemente.

**Comment by Gabriel-Assuncao** [comment]
Prezado Hugo Macedo, bom dia.
Agradeço por esta nova informação, mas vou optar pela primeira opção neste momento, pois uma mudança de pacote seria bastante trabalhoso neste momento.

**Comment by hhmacedo** [comment]
Oi, @Gabriel-Assuncao, acho que me precipitei em dizer que faria funcionar. Instalei a nova versão do pacote para testar e infelizmente ele faz superar a etapa em que dava erro mas para em um novo erro numa etapa seguinte, do `download.file()`. O único download que ele consegue fazer é usando o protocolo ftp:// no link do IBGE, tentei com http:// ao invés do https:// e também não funcionou. 😢

**Comment by Gabriel-Assuncao** [comment]
Prezado Hugo Macedo, bom dia.
De qualquer forma, foi importante a atualização do pacote, para corrigir o problema pelo menos na etapa referente ao RCurl.
Sobre o novo problema, precisamos averiguar se existe alguma solução aplicável, ou se a única solução seria uma eventual migração de pacote.
Uma dúvida, qual erro está retornando no uso da função download.file()? Pois, eventualmente pode ser erro de timeout, ainda mais que hoje está tendo divulgação do Censo e disponibilização de dados no servidor, ocasionando uma demora no tempo de resposta, algo que sempre ocorre durante as divulgações.
Se o erro estiver relacionado a diferença entre tamanho do arquivo baixado para tamanho reportado, basta usar a função options(timeout=3600) antes de executar a função get_pnadc.

**Comment by hhmacedo** [comment]
O erro que dá ao tentar baixar usando o caminho com o https é:
```
> utils::download.file(url = "https://ftp.ibge.gov.br/Trabalho_e_Rendimento/Pesquisa_Nacional_por_Amostra_de_Domicilios_continua/Trimestral/Microdados/2022/PNADC_032022.zip", destfile = "PNADC_032022.zip")
tentando a URL 'https://ftp.ibge.gov.br/Trabalho_e_Rendimento/Pesquisa_Nacional_por_Amostra_de_Domicilios_continua/Trimestral/Microdados/2022/PNADC_032022.zip'
Error in utils::download.file(url = "https://ftp.ibge.gov.br/Trabalho_e_Rendimento/Pesquisa_Nacional_por_Amostra_de_Domicilios_continua/Trimestral/Microdados/2022/PNADC_032022.zip",  : 
  não foi possível abrir a URL 'https://ftp.ibge.gov.br/Trabalho_e_Rendimento/Pesquisa_Nacional_por_Amostra_de_Domicilios_continua/Trimestral/Microdados/2022/PNADC_032022.zip'
Além disso: Warning message:
In utils::download.file(url = "https://ftp.ibge.gov.br/Trabalho_e_Rendimento/Pesquisa_Nacional_por_Amostra_de_Domicilios_continua/Trimestral/Microdados/2022/PNADC_032022.zip",  :
  URL 'https://ftp.ibge.gov.br/Trabalho_e_Rendimento/Pesquisa_Nacional_por_Amostra_de_Domicilios_continua/Trimestral/Microdados/2022/PNADC_032022.zip': status was 'SSL connect error'
```
Tentei mudar o timeout e usar o http, mas também não funcionou:
```
> options(timeout = 3600)
> utils::download.file(url = "http://ftp.ibge.gov.br/Trabalho_e_Rendimento/Pesquisa_Nacional_por_Amostra_de_Domicilios_continua/Trimestral/Microdados/2022/PNADC_032022.zip", destfile = "PNADC_032022.zip")
tentando a URL 'http://ftp.ibge.gov.br/Trabalho_e_Rendimento/Pesquisa_Nacional_por_Amostra_de_Domicilios_continua/Trimestral/Microdados/2022/PNADC_032022.zip'
Error in utils::download.file(url = "http://ftp.ibge.gov.br/Trabalho_e_Rendimento/Pesquisa_Nacional_por_Amostra_de_Domicilios_continua/Trimestral/Microdados/2022/PNADC_032022.zip",  : 
  não foi possível abrir a URL 'http://ftp.ibge.gov.br/Trabalho_e_Rendimento/Pesquisa_Nacional_por_Amostra_de_Domicilios_continua/Trimestral/Microdados/2022/PNADC_032022.zip'
Além disso: Warning message:
In utils::download.file(url = "http://ftp.ibge.gov.br/Trabalho_e_Rendimento/Pesquisa_Nacional_por_Amostra_de_Domicilios_continua/Trimestral/Microdados/2022/PNADC_032022.zip",  :
  URL 'http://ftp.ibge.gov.br/Trabalho_e_Rendimento/Pesquisa_Nacional_por_Amostra_de_Domicilios_continua/Trimestral/Microdados/2022/PNADC_032022.zip': Timeout of 3600 seconds was reached
```
O download funciona quando o início do link é ftp://
```
> utils::download.file(url = "ftp://ftp.ibge.gov.br/Trabalho_e_Rendimento/Pesquisa_Nacional_por_Amostra_de_Domicilios_continua/Trimestral/Microdados/2022/PNADC_032022.zip", destfile = "PNADC_032022.zip")
tentando a URL 'ftp://ftp.ibge.gov.br/Trabalho_e_Rendimento/Pesquisa_Nacional_por_Amostra_de_Domicilios_continua/Trimestral/Microdados/2022/PNADC_032022.zip'
Content type 'unknown' length 210055856 bytes (200.3 MB)
> file.exists("PNADC_032022.zip")
[1] TRUE
```
Então acho que uma possível solução seria criar um parâmetro de protocolo, com padrão "https" mas aceitando "ftp", que entrasse no começo do `paste0()` do link de download.

**Comment by Gabriel-Assuncao** [comment]
Prezado Hugo Macedo, bom dia.
Então, na verdade antigamente o pacote utilizava somente o protocolo "ftp" para acessar os microdados, mas houveram mudanças nas regras onde foi necessária a migração para o protocolo "https", se não me engano orientações do próprio CRAN, daí por isso fizemos a mudança e migração. Inclusive, o acesso via "ftp" não estava mais funcionando corretamente.
Assim, precisamos avaliar com maior detalhe este mudança, pois ela é mais complexa diante do cenário de migração pelo qual passamos anteriormente, então isto teria que ficar para uma versão futura do pacote, mas iremos averiguar isso assim que for possível.
Mais uma vez gostaria de agradecê-lo pelo feedback e apoio prestados sobre a situação em questão e aproveito para parabenizar também pelo trabalho realizado no pacote dnads.

**Comment by hhmacedo** [comment]
Oi, Gabriel, começando pelo fim, obrigado pelo elogio do pacote, eventualmente pretendo voltar a olhar pra ele e me dedicar de forma a conseguir botar ele no CRAN, por enquanto fiz mais como quebra-galho.

Consegui uma opção para fazer o download via https, mas precisa de um pacote extra (o httr2). Você precisaria ver se prefere adicionar um outro parâmetro pra fazer a alternar entre as duas formas de download ou se adiciona esse novo meio de download como padrão e aí o parâmetro ficaria desnecessário:
```
> link <- "https://ftp.ibge.gov.br/Trabalho_e_Rendimento/Pesquisa_Nacional_por_Amostra_de_Domicilios_continua/Trimestral/Microdados/2022/PNADC_032022.zip"
> file <- basename(link)
> 
> link |>
+   httr2::request() |>
+   httr2::req_progress() |>
+   httr2::req_perform(path = file)
<httr2_response>                                      
GET
https://ftp.ibge.gov.br/Trabalho_e_Rendimento/Pesquisa_Nacional_por_Amostra_de_Domicilios_continua/Trimestral/Microdados/2022/PNADC_032022.zip
Status: 200 OK
Content-Type: application/zip
Body: On disk PNADC_032022.zip (210055856 bytes)
```

**Comment by Gabriel-Assuncao** [comment]
Prezado Hugo Macedo, boa tarde.
Agradeço imensamente pelo compartilhamento do código, creio que de fato o melhor caminho será a migração para o pacote httr2, que já até havia sido citado como algo que tem acontecido naturalmente.
No entanto, como isso exige uma reformulação mais completa do código do pacote e como acabei de submeter uma nova versão no CRAN, deixarei esta implementação para o futuro, assim que for possível.

**Comment by Gabriel-Assuncao** [comment]
Prezado Hugo Macedo, boa noite.
Uma última informação que acabei esquecendo de fornecer é que provisoriamente podem ser utilizadas as funções do pacote para leitura dos microdados de forma offline, sendo que primeiramente é preciso que o usuário faça o download de forma independente dos arquivos dos microdados direto do portal do IBGE, para os microdados trimestrais através do endereço: [https://ftp.ibge.gov.br/Trabalho_e_Rendimento/Pesquisa_Nacional_por_Amostra_de_Domicilios_continua/Trimestral/Microdados/](https://ftp.ibge.gov.br/Trabalho_e_Rendimento/Pesquisa_Nacional_por_Amostra_de_Domicilios_continua/Trimestral/Microdados/) e para os microdados anuais através do endereço: [https://ftp.ibge.gov.br/Trabalho_e_Rendimento/Pesquisa_Nacional_por_Amostra_de_Domicilios_continua/Anual/Microdados/](https://ftp.ibge.gov.br/Trabalho_e_Rendimento/Pesquisa_Nacional_por_Amostra_de_Domicilios_continua/Anual/Microdados/).
Então após tal processo basta utilizar a função _read_pnadc_, e de forma consecutiva se for do interesse do usuário, utilizar as funções _pnadc_labeller_ e _pnadc_deflator_, e por fim utilizar a função _pnadc_design_ para incorporação do desenho amostral.

**Comment by hhmacedo** [comment]
Ah sim, eu já sabia dessa parte, mas como vou trabalhar com todos os anos da PNADC, estava tentando um último suspiro a fazer isso de forma automatizada e simples. O código estava bonitinho dentro de um loop bem simples, mas como essa conexão parou de funcionar acabou que meu loop ficou inutilizado.
Não queria baixar uma a uma manualmente, mas confirmei hoje que um dos servidores onde trabalho já tem essas bases baixadas, então agora vou trabalhar para reorganizar meu código trocando o get por um list+read. (Porém preciso confessar que estou cogitando dar um clone no repositório do PNADcIBGE e trocar o download.file pelo httr2 pra meu uso interno mesmo.)

**Comment by Gabriel-Assuncao** [comment]
Prezado Hugo Macedo, boa noite.
Perfeito, qualquer coisa permaneço à disposição.

**Comment by hhmacedo** [comment]
Para quem estiver com problema semelhante, vou deixar aqui uma sugestão de como instalar uma versão modificada do pacote seguido de um exemplo de download de um trimestre.
```R
pak::pkg_install("hhmacedo/PNADcIBGE@httr2")
httr::set_config(httr::config(ssl_verifypeer=0L))
library(PNADcIBGE)
pnadc <- get_pnadc(year = 2024, quarter = 3, curlopts = list(ssl.verifypeer = FALSE))
```

**Comment by Gabriel-Assuncao** [comment]
@hhmacedo, bom dia.

Agradecemos imensamente pela contribuição, inclusive já havíamos preparado também uma versão alternativa para transição da utilização dos pacotes httr e RCurl para a utilização somente do pacote httr2, porém na época que estávamos elaborando esta adaptação o pacote httr2 estava com um problema de submissão no CRAN, daí optamos por trazer esta versão mais para o futuro, mas de qualquer forma, estaremos disponibilizando esta versão alternativa através do endereço: [drive.ibge-SIPD-HTTR2](https://drive.ibge.gov.br/s/NSNcY9AXE3rPzaW), para acessar o compartilhamento é preciso inserir a senha **WVDN[6ox4]**.

**Comment by hhmacedo** [comment]
Oi, @Gabriel-Assuncao, boa tarde. 

Eu postei essa "solução" aqui só pra ficar documentada de alguma forma mesmo. Eu tinha criado esse branch modificado para uso próprio e de pessoas próximas, porém fui testar ontem e não estava conseguindo usá-lo. Ao conseguir usar hoje, achei que poderia ser útil não só pra mim e por isso deixei a solução aqui ligada ao issue. De qualquer forma, fico contente em saber que o IBGE terá uma solução própria, o instituto tem evoluído bastante nos últimos anos na divulgação das informações. 

Abraços!

**Comment by Gabriel-Assuncao** [comment]
@hhmacedo, boa tarde.

Ficamos felizes pelo reconhecimento do nosso trabalho e aproveitamos para agradecê-lo pela troca de informações realizadas ao longo desta issue, que foram fundamentais para iniciarmos esse processo de desenvolvimento da nova função.
