### ISSUE TITLE
Dúvida sobre a falta das variáveis "Capital" e "RM_RIDE"

### ISSUE THREAD

**Issue by femdias** [Gabriel-Assuncao/PNADcIBGE#18]
Olá, @Gabriel-Assuncao, tudo bem? Primeiramente, obrigado pelo seu trabalho com essa biblioteca!

Gostaria de saber o porquê de não haver as variéveis "Capital" e "RM_RIDE" nos microdados extraídos com essa biblioteca. Essas duas variáveis estão presentes nos microdados quando baixo manualmente.

Agradeço a atenção!

**Comment by Gabriel-Assuncao** [comment]
Prezado Felipe Dias, bom dia.
Peço por gentileza que envie o código que está sendo utilizado para obtenção dos microdados, pois tais variáveis são obtidas sim durante o processo de captação dos microdados com a utilização do pacote, mas pode ser que em seu código esteja sendo fornecido valor para o argumento vars, e aí realmente são mantidas somente as variáveis essenciais para os processos internos de deflacionamento e incorporação do desenho amostral, como UF por exemplo, e estas outras variáveis são excluídas ao fornecer tal argumento, uma possibilidade seria simplesmente de não utilizar o argumento vars.
De qualquer forma, com o código que será fornecido poderei verificar melhor o que pode estar acontecendo.
Assim, fico no aguardo do envio, para que eu possa lhe auxiliar de maneira mais efetiva e precisa.

**Comment by Gabriel-Assuncao** [comment]
Prezado @femdias, boa tarde.
Provavelmente a indisponibilidade de tais variáveis em sua execução tenha sido por conta do fornecimento de valor para o argumento vars da função get_pnadc do pacote PNADcIBGE, pois realizamos o teste de código abaixo e tivemos êxito na observação de tais variáveis:

install.packages("PNADcIBGE")
library("PNADcIBGE")
pnadc <- get_pnadc(year=2023, quarter=3)
table(pnadc$variables$RM_RIDE)
table(pnadc$variables$Capital)

Assim, solicito que verifiquei novamente e caso consiga acessar estas variáveis me avise por aqui, dando conclusão (fechando) se possível a esta issue.

**Comment by femdias** [comment]
Boa tarde, @Gabriel-Assuncao . Você tem toda razão, eu estava usando a library de forma errada. Muito obrigado pela resposta e desculpe pelo incômodo.
