### ISSUE TITLE
Problema no download do segundo trimestre de 2023 da PNAD anual

### ISSUE THREAD

**Issue by SantiagoLab** [Gabriel-Assuncao/PNADcIBGE#19]
Olá, tudo bem?

Eu estou tentando importar os dados do segundo trimestre de 2023 da PNAD anual com a função get_pnadc, mas quando a função procura pelo arquivo deflator desse período ocorre um erro por arquivo não encontrado. A saída no console foi a seguinte:

trying URL 'https://ftp.ibge.gov.br/Trabalho_e_Rendimento/Pesquisa_Nacional_por_Amostra_de_Domicilios_continua/Anual/Microdados/Trimestre/Trimestre_2/Dados/PNADC_2023_trimestre2.zip'
Content type 'application/zip' length 232426675 bytes (221.7 MB)
downloaded 221.7 MB

trying URL 'https://ftp.ibge.gov.br/Trabalho_e_Rendimento/Pesquisa_Nacional_por_Amostra_de_Domicilios_continua/Anual/Microdados/Trimestre/Trimestre_2/Documentacao/input_PNADC_trimestre2_20221221.txt'
Content type 'text/plain; charset=UTF-8' length 48453 bytes (47 KB)
downloaded 47 KB

trying URL 'https://ftp.ibge.gov.br/Trabalho_e_Rendimento/Pesquisa_Nacional_por_Amostra_de_Domicilios_continua/Anual/Microdados/Trimestre/Trimestre_2/Documentacao/dicionario_PNADC_microdados_trimestre2_20240322.xls'
Content type 'application/vnd.ms-excel' length 524288 bytes (512 KB)
downloaded 512 KB

Deflator data unavailable for selected year and period, so deflator year was changed to 2023 and period was changed to 2.
trying URL 'https://ftp.ibge.gov.br/Trabalho_e_Rendimento/Pesquisa_Nacional_por_Amostra_de_Domicilios_continua/Anual/Microdados/Trimestre/Trimestre_2/Documentacao/.xls'
Error in utils::download.file(url = paste0(ftpdir, "Trimestre_", defperiod,  : 
  cannot open URL 'https://ftp.ibge.gov.br/Trabalho_e_Rendimento/Pesquisa_Nacional_por_Amostra_de_Domicilios_continua/Anual/Microdados/Trimestre/Trimestre_2/Documentacao/.xls'
In addition: Warning messages:
1: In utils::download.file(url = paste0(ftpdir, "Trimestre_", defperiod,  :
  downloaded length 0 != reported length 196
2: In utils::download.file(url = paste0(ftpdir, "Trimestre_", defperiod,  :
  cannot open URL 'https://ftp.ibge.gov.br/Trabalho_e_Rendimento/Pesquisa_Nacional_por_Amostra_de_Domicilios_continua/Anual/Microdados/Trimestre/Trimestre_2/Documentacao/.xls': HTTP status was '404 Not Found'

Existe alguma alternativa para a importação desse banco com a aplicação do deflator ou alguma previsão de inserção desse arquivo?

Obrigado!

**Comment by Gabriel-Assuncao** [comment]
Prezado @SantiagoLab, boa tarde.

Realmente houve uma falha e o arquivo que deveria ter sido publicado não portal ainda não está disponível, já entramos em contato com a equipe responsável e assim que tal arquivo for disponibilizado entraremos em contato para lhe informar.

Aproveitamos a oportunidade para agradecê-lo pela informação e pedir desculpas pelo inconveniente.

Agradecemos pela atenção e nos colocamos a disposição para qualquer eventualidade.

Atenciosamente,
Gabriel Henrique Oliveira Assunção.

**Comment by SantiagoLab** [comment]
Boa tarde!

Eu que agradeço pela atenção e pela rapidez no retorno!

**Comment by Gabriel-Assuncao** [comment]
Prezado @SantiagoLab, bom dia.

Devido ao feriado e final de semana, este problema deve ser resolvido somente ao longo da semana que vem, mas de qualquer forma lhe aviso assim que o arquivo ficar disponível no servidor FTP do IBGE.

Agradecemos pela atenção e nos colocamos a disposição para qualquer eventualidade.

Atenciosamente,
Gabriel Henrique Oliveira Assunção.

**Comment by SantiagoLab** [comment]
Bom dia @Gabriel-Assuncao.

Sem problemas, muito obrigado!

**Comment by Gabriel-Assuncao** [comment]
Prezado @SantiagoLab, bom dia.

Informamos que o arquivo de deflatores que estava ausente no servidor, foi publicado hoje (02/04/2024) às 08:46. Inclusive, realizamos um teste e conseguimos obter os microdados com êxito, assim indicamos que já é possível o prosseguimento com suas rotinas habituais.

Aproveitamos para agradecê-lo mais uma vez pela informação fornecida que foi essencial para identificar a ausência deste arquivo.

Assim, estamos respondendo com esta mensagem já com o fechamento desta _issue_, qualquer coisa que precisar fique à vontade para entrar em contato através do canal de atendimento pacotesipd@ibge.gov.br.

Atenciosamente,
Gabriel Henrique Oliveira Assunção.
