### ISSUE TITLE
Função retorna todos os dados

### ISSUE THREAD

**Issue by Vergiel-a** [Gabriel-Assuncao/PNADcIBGE#2]
Olá. Estou com dificuldades em selecionar variáveis diretamente através da função `get_pnadc`. Mesmo utilizando o código de exemplo do pacote, é retornado todos os dados do pnadc do ano selecionado dentro da função, ao invés de somente das variáveis escolhidas. 

Sempre que se utiliza 

`get_pnadc(year=2017, quarter=4, vars = c("vd4001","vd4002"))` 

retorna todos os dados de todas as variáveis do ano de 2017 no quarto trimestre.

Aconteceu alguma mudança nos nomes das variáveis ou outra coisa? Pode ajudar?

**Comment by Gabriel-Assuncao** [comment]
Prezado Luiz Henrique, boa tarde.

É importante indicar que o software R é _case sensitive_, ou seja, existe diferenciação entre letras minúsculas e maiúsculas, então o correto é utilizar o código da seguinte forma:

`get_pnadc(year=2017, quarter=4, vars=c("VD4001","VD4002"))`

Fiz os testes utilizando o código acima e foram retornado os microdados somente com as variáveis indicadas, além das variáveis essenciais para as demais etapas dos processos que envolvem os microdados da PNAD Contínua, como inserção dos deflatores e incorporação do desenho amostral (incluindo as 200 variáveis de peso Bootstrap referente à nova ponderação da pesquisa).

Espero que com os pontos indicados seja possível obter os microdados da forma desejada.
