### ISSUE TITLE
get_pnad() não funcionando para anos além de 2023 (interview = 2)

### ISSUE THREAD

**Issue by EnriqPav** [Gabriel-Assuncao/PNADcIBGE#21]
Estou tentando acessar o modulo de turismo. Quando rodo essa linha para 2023 funciona:

`A <- get_pnadc(year = 2023, interview = 2)`

Qualquer outro ano, não:

`A <- get_pnadc(year = 2020, interview = 2)`

Error in if (reload == FALSE & file.exists(paste0(savedir, "/", inputpre))) { : 
  the condition has length > 1

**Comment by Gabriel-Assuncao** [comment]
Prezado @EnriqPav, boa noite.

Realizamos uma verificação relacionada ao erro apresentado e percebemos que tal erro está ocorrendo devido a duplicação dos arquivos de input e de dicionário para os microdados anuais acumulados na 2ª visita nos anos de 2020 e 2021.

Já fizemos a comunicação com a equipe responsável pela disponibilização dos arquivos através do servidor FTP do IBGE e assim que obtivermos uma solução por parte de tal área, entraremos em contato para avisá-lo.

Aproveitamos para agradecê-lo pelo alerta realizado e informá-lo que permanecemos à disposição para qualquer eventualidade.

**Comment by Gabriel-Assuncao** [comment]
Prezado @EnriqPav, bom dia.

Informamos que os arquivos duplicados já foram removidos pela equipe no servidor FTP do IBGE, inclusive já realizamos uma etapa de testes para obtenção dos microdados anuais acumulados na 2ª visita para os anos de 2020, 2021 e 2023, referentes ao módulo de Turismo, e conseguimos obter sem os erros que eram indicados anteriormente.

Assim, estaremos fechando esta _issue_ e qualquer dúvida ou problema, permanecemos à disposição através do canal de atendimento: pacotesipd@ibge.gov.br.

Agradecemos mais uma vez pelo contato e pela informação fornecida que foi fundamental para que pudéssemos corrigir tal problema.
