### ISSUE TITLE
`read_pnadc` não funciona para selecionar variáveis

### ISSUE THREAD

**Issue by filipemsc** [Gabriel-Assuncao/PNADcIBGE#22]
Tentei usar o argumento `vars` do pacote para ler um arquivo local e aparentemente não funciona.

```
file <- "PNADC_012024.txt"
input <- "input_PNADC_trimestral.txt"
vars <- c("Ano", "Trimestre", "UF","V1008", "V2003", "V1028001")

PNADcIBGE::read_pnadc(file, input, vars)
```

**Comment by Gabriel-Assuncao** [comment]
Prezado @filipemsc, bom dia.

Gostaria de entender melhor a indicação do problema, pois se for um erro que está sendo exibido, peço por gentileza que me indique qual o erro para que eu possa avaliar.

No entanto, se o problema estiver relacionado a quantidade de variáveis que permanece nos microdados mesmo após o recorte solicitado, indico que na verdade não é um problema, mas sim porque mesmo o usuário indicando determinadas variáveis para permanecer com o uso do argumento vars, mantemos também as variáveis que são essenciais para a incorporação do desenho amostral, como por exemplo as 200 variáveis de peso replicado que são fundamentais em tal etapa.

Assim, indicamos que realize um teste sem utilizar o argumento vars e utilizando o argumento vars, se houver diferença entre a quantidade de variáveis observadas, então quer dizer que o recorte está funcionando e a quantidade eventualmente elevada de variáveis que ainda permanecem está relacionada a esta necessidade de manutenção para a correta incorporação do desenho amostral.

Fico portanto no aguardo do retorno com as informações solicitadas para que eu possa concluir o atendimento.

Sendo assim, agradeço imensamente pela atenção e me coloco à disposição para qualquer eventualidade.
