### ISSUE TITLE
Erro no get_pnadc

### ISSUE THREAD

**Issue by mharduim** [Gabriel-Assuncao/PNADcIBGE#24]
Olá, Gabriel!

Inicialmente, eu tive a dificuldade de instalar o pacote, por conta do pacote dependente "httr2" que dava erro. Eu procurei algumas soluções e a que funcionou foi instalar o pacote PNADcIBGE na versão binária, por esse código:

`install.packages("PNADcIBGE", type = "binary", repos = "http://cran.r-project.org")`

Após instalar o pacote, fui testar a função get_pnadc, mas aparece o seguinte erro pra mim

> Error in function (type, msg, asError = TRUE)  : 
>   error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version

Eu já atualizei o pacote "openssl", mas não funcionou. Pode me ajudar?

**Comment by Gabriel-Assuncao** [comment]
Prezado @mharduim, bom dia.

Agradecemos pelo envio desta informação, percebemos que esse problema está relacionado possivelmente com a rede ou ambiente (sistema operacional e softwares) do usuário, inclusive já havíamos recebido relatos semelhantes conforme atendimentos em [https://github.com/Gabriel-Assuncao/PNADcIBGE/issues/10](https://github.com/Gabriel-Assuncao/PNADcIBGE/issues/10) e [https://github.com/Gabriel-Assuncao/PNADcIBGE/issues/17](https://github.com/Gabriel-Assuncao/PNADcIBGE/issues/17).

Verificando na internet possíveis soluções, é indicada a atualização dos pacotes _httr_, _RCurl_ e _curl_, mas pode ser que ainda assim seja vivenciado o mesmo erro relacionado ao protocolo SSL.

Até o momento não conseguimos ainda uma solução ótima para implementação na função _get_pnadc_ do pacote _PNADcIBGE_ para evitar este problema, inclusive há um tempo havíamos incluído um argumento em tal função indicado por _curlopts_, que os usuário podem utilizar fornecendo opção específicas do pacote _curl_ para evitar o problema, só que esta solução não é universal e para alguns usuários o problema não é resolvido.

Assim, infelizmente a solução que temos indicado aos usuários que vivenciaram este problema seria a tentativa de utilização da função _get_pnadc_ em uma outra rede ou em outro ambiente de computador, ou uma outra saída seria realizar a leitura dos microdados utilizando as funções de leitura _offline_, no caso através das funções _read_pnadc_, _pnadc_labeller_, _pnadc_deflator_ e _pnadc_design_.

Sentimos em não conseguir auxiliá-lo de maneira mais efetiva, mas caso precise de orientações de como realizar a leitura de forma _offline_ ou se precisar de atendimento com outras requisições, pedimos por gentileza que entre em contato através do canal de atendimento: [pacotesipd@ibge.gov.br](mailto:pacotesipd@ibge.gov.br).

Diante disso, iremos fechar essa _issue_, mas permanecemos à disposição através do canal de atendimento indicado acima.

Atenciosamente,
Suporte Pacotes SIPDIBGE, PNADcIBGE, PNSIBGE e COVIDIBGE.

**Comment by Gabriel-Assuncao** [comment]
Prezado @mharduim, boa noite.

Realizamos agora um teste em um computador mais antigo e vivenciamos o mesmo problema apresentado em sua mensagem, mas após atualizar a versão do software R em tal computador, o erro parou de ocorrer.

Então, como solução adicional, orientamos atualizar a versão do software R, certificando que esteja na versão 4.4.1 caso esteja utilizando o sistema operacional Windows, que é a versão mais recente disponível atualmente.

Qualquer nova ocorrência ou informação, permanecemos à disposição através do canal de atendimento indicado na mensagem anterior.
