### ISSUE TITLE
Não consigo baixar os dados da PNADC anual concentrada no segundo trimestre (erro "std::bad_aloc")

### ISSUE THREAD

**Issue by pedromarques-polsci** [Gabriel-Assuncao/PNADcIBGE#25]
Olá, espero que esta mensagem o encontre bem. Eu não consigo baixar dados da PNADC anual concentrada no segundo trimestre. Quando executo a função get_pnadc(topic = 2), o arquivo dos microdados e o input são baixados, mas logo após isso, meu computador fica muito lento, e o R crasha ou me dá o erro "std::bad_aloc".

Tentei usar o método offline e o erro persistiu.

Atenciosamente.

**Comment by Gabriel-Assuncao** [comment]
Prezado @pedromarques-polsci, bom dia.

O erro indicado de "std::bad_aloc" está relacionado a insuficiência de memória para alocação das rotinas e objetos gerados durante o processo de obtenção dos microdados.

Como foi informado que o erro está ocorrendo tanto na leitura _online_, quanto na leitura _offline_, gostaríamos primeiramente que nos informasse se o erro na leitura _offline_ ocorre logo na utilização da função _read_pnadc_, ou está acontecendo no uso de outra função deste processo.

Outro ponto relevante que precisamos saber é a quantidade de memória RAM disponível no computador onde está sendo executada a rotina e se durante o processo outros softwares como Google Chrome estavam abertos, pois pode estar tendo um conflito no uso da memória RAM que prejudica o processo, principalmente pelo sintoma de lentidão indicado.

Além disso, gostaríamos de saber o ano onde está sendo observado o erro para o recorte dos microdados anuais concentrados no 2º trimestre, pois se eventualmente estiver sendo no ano de 2022 existe um agravante, pois neste recorte em específico também foi coletado o tema e tópico suplementar de 'Atenção primária à saúde' aumentando significativamente o tamanho dos arquivos relacionados aos microdados, o que pode estar influenciando também no erro de insuficiência de memória.

Diante disso, gostaríamos por fim de solicitar que estas informações sejam enviadas por gentileza ao canal de atendimento [pacotesipd@ibge.gov.br](mailto:pacotesipd@ibge.gov.br), para que possamos prosseguir com o atendimento por tal meio, com isso iremos fechar essa _issue_, mas permanecemos à disposição no canal indicado.

Atenciosamente,
Suporte Pacotes SIPDIBGE, PNADcIBGE, PNSIBGE e COVIDIBGE.
