### ISSUE TITLE
Error in substr(X1, 1, 1) : invalid multibyte string, element 1

### ISSUE THREAD

**Issue by jpandraderosa** [Gabriel-Assuncao/PNADcIBGE#3]
As função read_pnadc esta dando erro para ler os dados. Acho que o dicionário está com o espaçamento errado, estou usando o que o proprio pacote baixa e o erro é logo no primeiro pipe da função

**Comment by Gabriel-Assuncao** [comment]
Olá João Pedro. Tudo bem contigo?

Este erro está ocorrendo, pois quando atualizamos o pacote PNADcIBGE em 30/11/2021, nós decidimos por fazer uma varredura completa no código avaliando todas as funções que estão sendo utilizadas, inclusive àquelas que são de outros pacotes e diante deste cenário verificamos que uma das funções que utilizávamos para leitura dos microdados iria se tornar obsoleta, então resolvemos alterá-la para a versão ativa, sendo que esta função faz parte do pacote readr, então basicamente o que precisa ser feito para corrigir tal problema é atualizar a versão do pacote readr utilizando o comando install.packages("readr") e após a realização de tal procedimento, o erro indicado será corrigido, sendo possível obter os microdados normalmente.

Aproveitamos para indicar a verificação constante da versão dos pacotes que estão sendo utilizados, e para o caso específico é necessário que a versão instalada do software R seja equivalente ou superior à '3.1', a versão do pacote PNADcIBGE deve ser igual ou superior à ‘0.7.0’ e a versão do pacote readr deve ser igual ou superior à ‘2.1.1’.

Esperamos que as informações acima sejam suficiente para sanar as questões apresentadas, no entanto, caso ainda haja alguma pendência, pedimos por gentileza que entre em contato com o canal de atendimento pacotesipd@ibge.gov.br. Então fecharemos esse issue e qualquer coisa estaremos a disposição pelo canal indicado anteriormente.
