### ISSUE TITLE
Não consigo subsetar com get_pnadc

### ISSUE THREAD

**Issue by Edilson-R** [Gabriel-Assuncao/PNADcIBGE#4]
Olá Gabriel.
Meu R é o 4.1.3 (2022-03-10) -- "One Push-Up", PNADcIBGE é o 0.7.0 e o readr é 2.1.2.
Acontece que quando executo o comando abaixo, não consigo um subset, mas toda a base.

dadosPNADc <- get_pnadc(year = 2019, interview = 1, design = FALSE, vars=c("Trimestre","UF","UPA","Estrato","V1008","V1030","V1031","V1032","posest","V2001","V2007","V2008","V20081","V20082","V2010","VD4020","VD4048"))

podes me ajudar??

**Comment by Gabriel-Assuncao** [comment]
Edilson, boa tarde. Tudo bem?

Na verdade o _subset_ a partir do argumento _vars_ na função _get_pnadc_ está funcionando perfeitamente, ocorre que por segurança deixamos as variáveis essenciais nos microdados mesmo que os usuários não as incluam dentro do vetor de valor do argumento _vars_, já que tais variáveis são fundamentais nas etapas de preparação dos microdados, ou seja, para rotulação das variáveis categóricas, para inserção dos índices deflacionamento e principalmente para incorporação do desenho amostral.

A princípio, pela quantidade de variáveis que é retornado após a execução do comando fornecido em sua mensagem, mais precisamente 228 variáveis, há o indicio de que o recorte solicitado não está sendo realizado, porém é importante ressaltar que após a reponderação da PNAD Contínua que ocorreu em 30 de novembro de 2021 foram incluídas nos microdados 200 variáveis correspondentes aos pesos de replicação via Bootstrap desta nova ponderação, e tais variáveis foram definidas como essenciais, justamente para incorporação do desenho amostral, ou seja, mesmo que o usuário não as inclua no vetor conforme informado anteriormente, a manutenção destas variáveis nos microdados é garantida.

Então, só para facilitar o entendimento, se por ventura executarmos o comando fornecido em sua mensagem sem o fornecimento do valor para o argumento _vars_, o objeto de microdados retornado possuirá 496 variáveis, ou seja, evidentemente no comando com a presença do argumento _vars_ estão sendo mantidas as 17 variáveis fornecidas no vetor mais as variáveis "Ano", "V1014", "V1034", "posest_sxi" e "V2003" que são consideradas essenciais, mais a variável "ID_DOMICILIO" que é criada para identificação do domicílio para utilização na incorporação do desenho amostral, mais as variáveis "CO1", "CO1e", "CO2", "CO2e" e "CO3" que são os índices de deflacionamento que foram inseridos pela omissão (_default_) do argumento _deflator_ na função _get_pnadc_ e mais as 200 variáveis dos pesos de replicação via Bootstrap, que somando coincidem com o total de variáveis observadas na execução do comando, ou seja, 228 variáveis.

Espero que as informações acima sejam suficiente para sanar as questões apresentadas, no entanto, caso ainda haja alguma pendência, peço por gentileza que entre em contato com o canal de atendimento [pacotesipd@ibge.gov.br](mailto:pacotesipd@ibge.gov.br). Então irei fechar esse issue e qualquer coisa estou a disposição pelo canal indicado anteriormente.
