### ISSUE TITLE
Acesso à pesquisa suplementar TIC

### ISSUE THREAD

**Issue by MatheusCPatrocinio** [Gabriel-Assuncao/PNADcIBGE#5]
Oi Gabriel, boa noite! Consigo acessar os microdados da pesquisa de acesso à internet, tv etc (TIC) até o ano de 2019 somente. Sabe me dizer por que não está disponível nos anos de 2020 ou 2021, ou se os nomes das variáveis tiveram mudanças? Desde já agradeço

**Comment by Gabriel-Assuncao** [comment]
Matheus, boa noite. Tudo bem?

Conforme consta no quadro temático histórico de temas e tópicos suplementares anuais da PNAD Contínua que pode ser acessado através do endereço: https://ftp.ibge.gov.br/Trabalho_e_Rendimento/Pesquisa_Nacional_por_Amostra_de_Domicilios_continua/Anual/Microdados/PNADC_Pesquisas_Suplementares_Anuais_20210414.pdf, a pesquisa suplementar referente à TIC só foi divulgada até o momento de 2016 à 2019, por este motivo através do pacote _PNADcIBGE_ só é possível obter os microdados referentes a tais períodos.

Aproveito para informar que para o ano de 2020, devido à pandemia do Coronavírus, onde foi necessária a adaptação da coleta por telefone, não foi investigado o módulo referente à pesquisa suplementar de TIC, tendo retornado para coleta em 2021, no entanto, neste momento ainda não existe uma data definida para divulgação dos resultados referentes a tal ano, assim que for definida a data de divulgação deste módulo, tal informação estará disponível no calendário de divulgações da pesquisa.

Espero que as informações acima sejam suficiente para sanar as questões apresentadas, no entanto, caso ainda haja alguma pendência, peço por gentileza que entre em contato com o canal de atendimento [pacotesipd@ibge.gov.br](mailto:pacotesipd@ibge.gov.br). Então irei fechar esse issue e qualquer coisa estou a disposição pelo canal indicado anteriormente.
