### ISSUE TITLE
Seção de Rendimentos?

### ISSUE THREAD

**Issue by mcs038** [Gabriel-Assuncao/PNADcIBGE#6]
Onde está a seção de Rendimentos? as variáveis v5* não estão aparecendo.

**Comment by Gabriel-Assuncao** [comment]
Prezado Matheus, boa noite. Tudo bem?

O módulo de rendimentos representado pelas variáveis iniciadas por 'V5...' faz parte dos microdados anuais acumulados em determinada visita, sendo coletado na primeira e na quinta visita, então para ter acesso a este tipo de microdados é preciso utilizar a função _get_pnadc_ do pacote _PNADcIBGE_ fazendo uso dos argumentos _year_ e _interview_, sendo que no argumento _year_ deve ser fornecido o ano de interesse dos microdados e para o argumento _interview_ deve ser fornecido o valor 1 ou 5, sendo importante indicar que para os anos de 2012 à 2019 é utilizado para divulgação pelo IBGE os microdados de 1ª visita, enquanto que para o ano de 2020 foi utilizado para divulgação pelo IBGE os microdados de 5ª visita, não tendo ocorrido até o momento a divulgação para o ano de 2021.

Lembrando que não é indicada a junção das bases de microdados anuais com as bases de microdados trimestrais, já que o fator de expansão e a incorporação do desenho amostral, necessários para obtenção dos resultados em nível populacional, são realizados de formas distintas nestes dois tipos de bases.

Espero que as informações acima sejam suficiente para sanar as questões apresentadas, no entanto, caso ainda haja alguma pendência, peço por gentileza que entre em contato com o canal de atendimento [pacotesipd@ibge.gov.br](mailto:pacotesipd@ibge.gov.br). Então irei fechar esse issue e qualquer coisa estou a disposição pelo canal indicado anteriormente.
