### ISSUE TITLE
Função `read_pnadc()` retorna todas as variáveis

### ISSUE THREAD

**Issue by fabricioferr** [Gabriel-Assuncao/PNADcIBGE#8]
Caros, estou com um problema ao utilizar a função `read_pnadc()`.
Estou utilizando os microdados da Pnad Contínua de 2019 para a minha dissertação. Todavia, neste mês quando fui fazer a leitura dos microdados da Pnad para variáveis selecionadas através da função `read_pnadc()`, o tibble que obtenho apresenta 216 variáveis. Fiz diversos testes a fim de verificar se era algum erro de digitação, mas mesmo assim o erro permanece.
Código utilizado:
` variables <- c("UF", "UPA", "Estrato", "V1008", "V1014","V1022", "V1032", 
               "V2001", "V2005", "V2007", "V2009", "V2010", "V3001", "VD3004",
               "VD3005", "V3009A", "VD5008", "VD4010", "VD2002")

pnad_continua <- PNADcIBGE::read_pnadc(
  microdata = "PNADC_2019_visita1.txt",
  input_txt = "input_PNADC_2019_visita1_20211130.txt",
  vars = variables
  ) `
Tibble resultante:
![image](https://user-images.githubusercontent.com/86859223/176559716-8b830e39-fc5b-4585-adc2-e1cea80dbd91.png)

Estou utilizando a versão 2.1.2 do pacote readr.

**Comment by Gabriel-Assuncao** [comment]
Fabrício, bom dia. Tudo bem?

Na verdade o recorte a partir do argumento vars na função _get_pnadc_ (e também para a função _read_pnadc_) está funcionando perfeitamente, ocorre que por segurança deixamos as variáveis essenciais nos microdados mesmo que os usuários não as incluam dentro do vetor de valor do argumento vars, já que tais variáveis são fundamentais nas etapas de preparação dos microdados, ou seja, para rotulação das variáveis categóricas, para inserção dos índices deflacionamento e principalmente para incorporação do desenho amostral.

A princípio, pela quantidade de variáveis que é retornado após a obtenção dos microdados de 1ª visita de 2019 pela função _get_pnadc_ com a utilização do argumento _vars_ para as variáveis indicadas em sua mensagem, mais precisamente 228 variáveis, há o indicio de que o recorte solicitado não está sendo realizado, porém é importante ressaltar que após a reponderação da PNAD Contínua que ocorreu em 30 de novembro de 2021 foram incluídas nos microdados 200 variáveis correspondentes aos pesos de replicação via _Bootstrap_ desta nova ponderação, e tais variáveis foram definidas como essenciais, justamente para incorporação do desenho amostral, ou seja, mesmo que o usuário não as inclua no vetor conforme informado anteriormente, a manutenção destas variáveis nos microdados é garantida.

Então, só para facilitar o entendimento, se por ventura executarmos o comando fornecido em sua mensagem sem o fornecimento do valor para o argumento vars, o objeto de microdados retornado possuirá 496 variáveis, ou seja, evidentemente no comando com a presença do argumento _vars_ estão sendo mantidas as 19 variáveis fornecidas no vetor mais as variáveis "Ano", "Trimestre", "V1030", "V1031", "V1034", "posest", "posest_sxi" e "V2003" que são consideradas essenciais, mais a variável "ID_DOMICILIO" que é criada para identificação do domicílio para utilização na incorporação do desenho amostral, mais as variáveis "CO1", "CO1e", "CO2", "CO2e" e "CO3" que são os índices de deflacionamento que foram inseridos pela omissão (default) do argumento deflator na função _get_pnadc_ e mais as 200 variáveis dos pesos de replicação via _Bootstrap_, que somando tem um total de 233 variáveis, como em seu processo está sendo utilizada a função _read_pnadc_ as variáveis de índices para deflacionamento (5 variáveis) naturalmente não existirão, então no seu caso deveriam existir 228 variáveis e não 216 variáveis conforme indicado, por isso é importante verificar a integridade dos microdados que estão sendo utilizados na função _read_pnadc_ e também confirmar se a versão do pacote _PNADcIBGE_ utilizada é igual ou superior a 0.7.0.

Espero que as informações acima sejam suficiente para sanar as questões apresentadas, no entanto, caso ainda haja alguma pendência, peço por gentileza que entre em contato com o canal de atendimento [pacotesipd@ibge.gov.br](mailto:pacotesipd@ibge.gov.br). Então irei fechar esse _issue_ e qualquer coisa estou a disposição pelo canal indicado anteriormente.
